apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: nodeops-pvc
  name: nodeops-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: nodeops
  name: nodeops
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      io.kompose.service: nodeops
  template:
    metadata:
      labels:
        io.kompose.service: nodeops
    spec:
      containers:
      - image: nodeops
        name: node-app
        ports:
        - containerPort: 3000
        resources: {}
        volumeMounts:
        - mountPath: /src
          name: nodeops-pvc
      hostname: node-app
      restartPolicy: Always
      volumes:
      - name: nodeops-pvc
        persistentVolumeClaim:
          claimName: nodeops-pvc
status: {}
