apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: nodeops
  name: nodeops
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      io.kompose.service: nodeops
  template:
    metadata:
      labels:
        io.kompose.service: nodeops
    spec:
      containers:
      - image: nodeops
        name: node-app
        ports:
        - containerPort: 3000
        resources: {}
        volumeMounts:
        - mountPath: /app/src
          name: nodeops-claim0
      hostname: node-app
      restartPolicy: Always
      volumes:
      - name: nodeops-claim0
        persistentVolumeClaim:
          claimName: nodeops-claim0
status: {}
