apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: k-s-skaffold
build:
  local: {}
  # tagPolicy:
  #   envTemplate:
  #     template: "{{.VERSION}}"
  artifacts:
  - image: nodeops
    docker:
      dockerfile: Dockerfile
    context: app
  - image: mongodb
    context: mongodb
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - .k8s/*.yaml
  # kubeContext: minikube
profiles:
  - name: docker-k8s
    deploy:
      kubeContext: docker-desktop
  - name: minikube
    activation:
      - kubeContext: minikube
  # - name: profile1
  #   activation:
  #     - env: MAGIC_VAR=42
  # - name: profile2
  #   activation:
  #     - env: MAGIC_VAR=1337
  #     - kubeContext: miniKube
  #       command: dev
  # - name: dev
  #   patches:
  #     - op: replace
  #       path: /build/artifacts/0/docker/dockerfile
  #       value: Dockerfile.dev
