apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: k-s-skaffold
build:
  artifacts:
  - image: nodeops
    context: app
  - image: mongodb
    context: mongodb
deploy:
  kubectl:
    manifests:
    - .k8s/*.yaml
